dolores = {
    "Atención al cliente": [
        "maltrato",
        "desatencion",
        "respuesta rapida",
        "rapida respuesta",
        "mala atencion",
        "call center", "operadora", "operador",
        "poco cortez", 
        "los que atienden",
        "no explican bien",
        "me atendieron mal",
        "reclamo",
        "No les interesa el cliente",
        "pesima atencion",
        "no escuchan",
        "representantes soberbios y maleducados",
        "destrato total",
        "pésima atención",
        "atienden sin ganas",
        "maltrato del empleado",
        "pesima gestion atención telefonica",
        "el asesor no tenía ganas de  hablar", "el asesor", "asesor",
        "los operadores son  nefastos al momento de explicar",
        "el operador me atendio de mala gana",
        "la atencion fue pedante y no resolutiva",
        "la atencion es pesima",
        "falta de seriedad",
        "respeto al cliente",
        "la atencion es una porquería",
        "la atención",
        "pesima atencion",
        "destrato",
        "falta de respeto",
        "grito",
        "no me escucho",
        "se ríe",
        "me corto",
        "no me atiende",
        "irrespetuoso",
        "mal educada",
        "falta de empatía",
        "asesoramiento",
        "no cuidan al cliente",
        "no brindan soluciones",
        "atención deficiente",
        "mal servicio de atención",
        "complicado dar de baja",
        "mal manejo con los clientes",
        "la baja es difícil",
        "demasiadas vueltas para resolver",
        "no me solucionan nada",
        "no ayudan al cliente",
        "esperar mucho para una respuesta",
        "no me llamaron",
        "prometieron llamarme y no lo hicieron",
        "me pasean de un área a otra",
        "el cliente no importa",
        "sin soluciones claras",
        "falsa promesa",
        "nunca responden los reclamos",
        "me mintieron",
        "no solucionan los errores que cometen",
        "poca claridad",
        "la atención", "la atencion"
    ],
    "Encuesta": [
        "comentarios", "solicitudes",
        "derivar a mensajes",
        "encuestas",
        "LA ENCUESTA"
    ],
    "Cadom": [
        "me mude",
        "mudanza",
        "cambio de domicilio",
    ],
    "Catit": [
        "cambio de titularidad",
        "el titular",
        "cambiar la titularidad", "titularidad"
    ],
    "Catec": [
        "cambio de decodificador",
        "cambio del modem",
        "módem",
        "la nueva tecnlogia",
        "cambio de deco",
        "no vino nadie",
        "nunca vinieron",
        "cambiar el equipo",
        "cambio de modem",
        "fibra",
        "fibra optica",
        "me cambiaron a fibra y funciona peor",
        "desde que me pasaron a fibra",
        "problemas con la instalación de fibra",
        "menos señal desde el cambio",
        "problemas técnicos tras el cambio",
        "problemas con el cambio de tecnología",
        "cambio de tecnología a fibra óptica",
        "fibra no funciona bien",
        "la señal es peor desde que cambiaron",
        "cambios que afectaron el servicio",
        "fallas en la instalación",
        "la instalación no se completó",
        "cambios sin explicaciones",
        "problemas por cambiar a fibra óptica",
        "cambio de servicio no solicitado"
    ],
    "Cobertura": [
        "cobertura",
        "no tengo cobertura",
        "no cubre"
    ],
    "Conveniencia": [
        "no hay relacion precio calidad",     
        "producto calidad",
        "elevado y calidad mal",
        "relacion costo servicio",
        "servicio muy caro",
        "el mas caro del mercado",
        "muy cara y se corta",
        "no funciona y es muy caro",
        "servicio malo y caro",
        "mal servicio y se corta",
        "carisimo el servicio",
        "deficiente servicio",
        "costo y servicio",
        "no recomendar",
        "no confiable",
        "pobre servicio",
        "atencion al cliente",
        "el servicio",
        "malisimo servicio y atencion"
        "cada vez más caro",
        "muy caro y funciona mal",
        "precio excesivo por lo que ofrecen",
        "relación precio calidad pésima",
        "el servicio no lo vale",
        "pago mucho y funciona mal",
        "precio elevado por mala calidad",
        "anda mal y es caro",
        "muy caro para lo que brindan",
        "muy costoso y anda mal",
        "mala calidad por precio",
        "se corta y es caro",
        "caro y se corta siempre",
        "mal funcionamiento y precio alto",
        "precio alto y servicio deficiente",
        "cobra mucho y no anda",
        "mal servicio por el precio",
        "está muy caro el servicio",
        "cada vez más caro y peor",
        "cobran una fortuna",
        "no es tan bueno",
        "sin internet",
        "no funciona",
        "se descompone",
        "sin comunicación"
    ],
    "Baja del Servicio": [
        "gestione baja",
        "baja del servicio",
        "dio de baja",
        "dar de baja",
        "pedi la baja",
        "la baja",
        "di de baja",
        "no dan de baja",
        "solicitar la baja",
        "baja el servicio", "se le dio de baja"
    ],
    "Cobre": [
        "cobre",
        "mega",
        "megas",        
        "fibra en la zona", 
        "cable de cobre",
        "banda ancha",
        "no llega a mi barrio", "barrio",
        "poco alcance",
        "digitalizaron", "digitalizacion"
    ],
    "Migración / Quiero Fibra": [
        "no tengo fibra óptica",
        "no tengo banda ancha",
        "aún no tengo fibra",
        "a mi zona todavía no llega la fibra",
        "nunca vinieron a colocar la fibra óptica",
        "no extendieron la red de fibra óptica",
        "no hay conexión con fibra óptica",
        "no llegó fibra óptica",
        "esperando que llegue la fibra",
        "estoy esperando fibra óptica",
        "años esperando fibra óptica",
        "hasta que no pongan fibra óptica",
        "no quieren colocarme fibra",
        "no me ofrecen fibra óptica",
        "no invierten en poner fibra óptica",
        "publicitan fibra óptica pero no llega",
        "solo tengo par de cobre",
        "estoy con el cable de cobre",
        "solo cuento con 6 megas",
        "tengo apenas 10 megas",
        "navego con 3 megas",
        "no pueden ofrecerme fibra",
        "zona de migración",
        "mi línea está en migración",
        "esperando la reconversión a fibra óptica",
        "esperando la solución para pasarme a fibra",
        "no saben cuándo llega la fibra",
        "prometieron fibra y nunca llegó",
        "me dijeron que iban a instalar fibra y no lo hicieron",
        "me prometieron fibra óptica",
        "solo tengo 2 megas",
        "banda ancha inexistente",
        "estaría bárbaro que traigan fibra óptica",
        "no funciona el servicio por cable",
        "tengo que esperar a que pase la fibra óptica",
        "no puedo disponer de fibra óptica",
        "cambio de tecnología y no tengo fibra",
        "están cambiando a fibra pero no llegó"
    ],
    "Band steering": [
        "wifi",
        "wi-fi",
        "señal",
        "dispositivos",
        "artefactos",
        "desvinculan",
        "5ghz",
        "2.4ghz",
    ],
    "Velocidad": [
        "Muy lento el Internet",
        "muy baja velocidad",
        "funciona lento",
        "lentitud",
        "muy lento",
        "lerda", "lerdo",
        "tarda muchisimo",
        "no hay velocidad",
        "conexion lenta",
        "conexion deficiente",
        "300 megas",
        "la velocidad de internet",
        "anda muy lenta",
        "falta velocidad",
        "anda muy lento", 
        "muy lerdo",
        "anda muy lenta"
        "no es rapida",
        "velocidad baja",
        "lenta", "lento",
        "llegan pocos megas",
        "velocidad inestable",
        "baja velocidad de bajada",
        "no es muy rapida",
        "velocidad", "rapida",
        "veloz"
    ],
    "Correo/Dominio/Fibertel": [
        "fibertel",
        "correo fibertel",
    ],
    "Precio": [
        "precio", "precios", "precio del servicio", "precio elevado", "precio alto", "precio excesivo",
        "caro", "cara", "carisimo", "carísimo", "carísima", "muy caro", "muy cara", "demasiado caro", "demasiado cara",
        "costoso", "costosa", "muy costoso", "muy costosa", "excesivamente caro", "excesivamente costoso",
        "es caro", "es cara", "es carísimo", "es muy caro", "es muy costoso", "está muy caro", "está muy cara",
        "suba de precio", "suben el precio", "aumenta el precio", "aumento de precio", "subida de precio",
        "costo", "costos", "costo elevado", "costos elevados", "costo altísimo", "costo muy alto", "costo muy elevado",
        "tarifa", "tarifa elevada", "tarifa alta", "tarifa mensual", "valor de la tarifa",
        "abono elevado", "abono muy caro", "abono mensual", "valor del abono",
        "aumentos", "aumenta todos los meses", "me aumentan", "aumentos constantes", "subas constantes",
        "es una estafa", "impagable", "injustificado", "imposible de pagar", "cada vez más caro",
        "no lo puedo pagar", "difícil de pagar", "ya no puedo pagarlo", "monto altísimo", "monto elevado",
        "me cobran", "me aumentaron", "subió el precio", "aumentan sin avisar", "sin previo aviso",
        "comparado con otras", "comparación con otras", "más barato en otro lado", "hay opciones más baratas",
        "pagando", "pago mucho", "me subieron", "subieron", "lo subieron", "suben", "suba", "subas",
        "presio", "presios", "pesio", "demaciado caro", "demasido caro", "exageradamente caro",
        "no se justifica el gasto", "valor excesivo", "relación costo", "relación precio", "costo-beneficio",
        "no se justifica lo que cobran", "valores altos", "factura elevada", "alta factura",
        "incremento de precio", "inflación", "ajustes mensuales", "monto elevado",
        "cada mes más caro", "más caro que", "cuesta mucho"
    ],
    "Competencia": [
        "starlink",
        "zona en que vivo",
        "unica opcion",
        "cambiar proveedor",
        "Claro",
        "pago menos",
        "la peor empresa",
        "otra empresa", "otras empresas",
        "las empresas"
    ],
    "Aviso Mora": [
        "cartel de corte",
        "se atrasa dias",
        "aviso de deuda", 
        "factura no corresponde",
        "cobranzas",
        "debo", "no debo",
        "sistema de cobro",
        "cobro", "cobran",
        "deuda", "deudor", "deudas",
        "reclamos por deuda"
    ],
    "Ajuste días sin servicio": [
        "se corta",
        "tiempo sin servicio",
        "sin servicio",
        "días sin servicio",
        "sin servicio",
        "descontar días sin servicio",
        "descontar",
        "cortado el servicio",
        "cortes de servicio",
        "falta de servicio",
        "no tengo servicio",
        "tiempo sin servicio"
    ],
    "Facturación": [
        "factura",
        "facturas",
        "factura vencida",
        "facturacion",
        "vencimiento",
        "cuota mensual", "cuota", "cuotas",
        "debito automatico",
        "cobran",
        "debitaron",
        "me cobraron dos veces",
        "factura errónea",
        "error en facturación",
        "cobraron",
        "facturando",
        "intereses",
        "desorden en la facturación",
        "facturación desastrosa",
        "facturación confusa",
        "notificacion",
        "facturan",
        "reclamo de deuda",
        "me están reclamando",
        "cobran lo que quieren",
        "precio del abono",
        "importe de la factura",
        "duplican la facturación",
        "desastres en la facturación",
        "no respetan precios",
        "no respetan promociones",
        "facturan servicios no contratados",
        "no cumplen lo pactado",
        "no hacen el descuento",
        "falta de bonificación",
        "facturan lo que quieren",
        "dan de alta servicios que no se piden",
        "descuento nunca aplicado",
        "promo sin descuento",
        "nunca recibí el descuento",
        "historial",
        "cambio de",
        "dar de",
        "me siguen cobrando",
        "nunca respetan el precio acordado",
        "me cobran cosas que no pedí",
        "no respetan lo pactado",
        "no cumplen lo prometido",
        "me cobran sin tener el servicio",
        "me cobran anticipado",
        "no puedo acceder a la factura",
        "problemas para ver la factura",
        "error de facturación",
        "me cobran servicios que no contraté",
        "me cobran de más todos los meses",
        "descuento aplicado y luego cobrado igual",
        "cobros automáticos no autorizados",
        "precio distinto al promocionado",
        "cobros inesperados",
        "errores sistemáticos en facturación",
        "problemas constantes con las facturas",
        "montos que no reconozco",
        "reclamo constante de facturación"
    ],
  "Indefinido": [
        "", " ", ".", "..", "...", "....", ".....",  # vacíos o solo símbolos
        "ok", "buena", "bueno", "conforme", "eficaz", "bueno.", "buena.", "ninguna",  # frases neutras sin contenido
        "po", "pt", "no pt",  # letras sueltas
        "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",  # números sueltos
        "nan", "none",  # si están presentes como texto en exportaciones
        "simplemete x la atenxion",  # sin sentido claro
        "pedorro", "mexes util", "me coetaron", "mal serv8cio",  # mal tipeo / ruido
        "no me", "no tengo", "no hay", "no dan", "nada", "es mi verdad", # frases truncas o ambiguas
        "por", "pq", "xq", "porque sí",  # explicaciones no desarrolladas
        "sin palabras", "un desastre", "pésimo", "horrible", "pésima señal",  # juicio sin argumento
        "pesimo el wifr", "q no es tannnn bueno cm parecia",  # ambigüedad o exageración vaga
        "todos a quien conozco tienen personal",  # sin queja clara
        "no entiendo que puse",   # sin información útil
        "ineficientes", "ineptos"  # insultos o generalizaciones vacías
],
    "Pasivos": [
        "buena conexión en general",
        "no he tenido inconvenientes significativos",
        "considero que es el término normal",
        "brindan buen servicio",
        "buen servicio bien la velocidad",
        "es recomendable",
        "ninguno. todo bien",
        "todo bien",
        "anda bien",
        "es aceptable",
        "está bien pero no es la gran cosa",
        "buena señal",
        "casi nunca tiene contratiempos",
        "que se tiene buena señal",
        "buen servicio pero",
        "no respetaron un acuerdo pero buen servicio"
    ],
    "Pagos": [
        "pago virtual",
        "no puedo pagar",
        "problemas para pagar",
        "pagar",
        "servicio limitado por falta de pago",
        "no sé cómo efectuar el pago",
        "pago",
        "pago virtual y rápida",
        "debito automático",
        "cobran mora",
        "tarjeta de credito",
        "visa",
        "descuentan cuando quieren",
        "confusa la posibilidad de abonar",
        "no puedo pagar con débito",
        "gestión de pago",
        "homebanking",
        "no logro pagar",
        "no se puede pagar",
        "cobro antes del vencimiento",
    ],
    "Atención Sucursal": [
        "en cabildo",
        "abasto",
        "oficina",
        "belgrano",
        "oficina de honduras"
    ],
    "Atención Servicio Técnico": [
        "el técnico",
        "los técnicos",
        "tecnica",
        "servicio técnico", "servicio tecnico",
        "demora", "turno",
        "problema técnico",
        "irresponsables",
        "poco calificado",
        "no se realizó ningún trabajo",
        "problemas cable",
        "inconveniente técnico",
        "reparaciones", "reparación",
        "el servicio tecnico",
        "mal servicio tecnico",
        "servicio tecnico deficiente",
        "no hay soporte", "solicitar un tecnico",
        "cita",
        "fue el tecnico", "vino el tecnico",
        "demora",
        "no vino el",
        "tardaron",
        "instalacion precaria",
        "instalacion",
        "no me lo instalan",
        "no me pusieron",
        "no pudieron instalarlo",
        "no la instalaron",
        "no pudieron terminar"
    ],
    "Cita Técnica": [
        "no vinieron",
        "no me avisaron",
        "agendado",
        "el equipo de agendamiento es un desastre",
        "visita",
        "no vienen",
        "no vino",
        "nadie vino",
        "visitas técnicas",
        "esperé toda la mañana",
        "me dijeron que reagende",
        "nunca me lo instalaron",
        "me dejaron plantado",
        "me dejaron plantada",
        "fueron a otro domicilio",
        "prometieron día y hora",
        "visitas pactadasni siquiera aparecieron",
        "bot avisó horas más tarde",
        "no cumplieron con la cita",
        "fallaron en la instalación",
        "no vino el técnico",
        "no apareció el técnico",
        "me dejaron esperando",
        "no cumplieron con la visita",
        "me dieron turno y no vinieron",
        "no vino nadie al domicilio",
        "me hicieron esperar todo el día",
        "prometieron venir y no vinieron",
        "cita reprogramada sin aviso",
        "cancelaron la visita",
        "no se presentó el técnico",
        "técnico nunca vino",
        "visita técnica incumplida",
        "esperé y no vinieron",
        "turno no cumplido",
        "prometieron visita que no ocurrió",
        "incumplieron la visita técnica",
        "nunca hicieron la instalación",
        "prometen venir"
    ],
    "Mail": [
        "me llego un mail", "salesforce",
        "me enviaron un mail", 
        "recibi un mail",
        "correo electronico",
        "los mail", "mails", "e-mail", "email",
        "mi correo"
    ],
    "Flow": [
        "flow",
        "no funciona flow",
        "nunca pude habilitar flow",
        "TV", "tv",
        "canales no se ven",
        "no tengo flow",
        "codificador", "codifcadores", "decodificador", "decodificadores",
        "nitidez", "imagen",
        "no puedo ver", "todo nublado",
        "streaming",
        "decodificador",
        "no se usar flow",
        "decodificadores",
        "control remoto",
        "guia",
        "grilla",
        "aplicacion flow", "app flow","app",
        "aplicacion",
        "canales",
        "no funciona el control remoto",
        "quiero fibra",
        "canal pago",
        "pelicula",
        "sacaron canales",
        "television",
        "programación caduca",
        "películas viejas",
        "repetición de programas",
        "programas repetidos",
        "contenido ya emitido",
        "canales que no se ven",
        "cambian horarios de series",
        "repetición de capítulos",
        "contenido desactualizado",
        "no tiene subtítulos",
        "no puedo ver programas anteriores",
        "problemas con el deco",
        "problemas para loguearme",
        "no se conecta flow",
        "problemas con la app de flow"
    ],
    "IVR": [
        "no atienden",
        "nadie me atiende",
        "me ponene en espera",
        "falta de atencion",
        "no me atienden",
        "atiende siempre una máquina",
        "atiende un contestador",
        "atención no personalizada",
        "contacto con la empresa",
        "no me atendieron",
        "nunca contesta una persona",
        "nunca me atienden",
        "no hay atención",
        "sin atención",
        "no hay con quién hablar",
        "nadie atiende",
        "nadie contesta",
        "nadie responde",
        "no contestan",
        "no te atiende nadie",
        "no puedo comunicarme",
        "no me puedo comunicar",
        "imposible comunicarse",
        "imposible hablar",
        "hablar con un humano",
        "imposible comunicarse con un operador",
        "no dispongo contacto con operador",
        "no hay forma de hablar con alguien",
        "es difícil comunicarse",
        "no dan la opción",
        "no me dan la opción que necesito",
        "no hay opción",
        "no existe la opción",
        "me pasaron con un contestador automático",
        "me contesta una máquina",
        "solo atiende un robot",
        "me atiende una máquina",
        "sólo atiende una computadora",
        "habla una grabación",
        "sistema automático",
        "atención automática",
        "menú automático",
        "opciones infinitas",
        "muchas opciones",
        "demora para hablar",
        "tardan en atender",
        "esperar mucho",
        "espera eterna",
        "espera larga",
        "20 horas para que atiendan",
        "llamás y nadie atiende",
        "llamás y no atienden",
        "llamé muchas veces y nada",
        "llamé 6 veces y nadie atiende",
        "llamé varias veces y no se comunicaron",
        "dificil comunicarse",
        "es muy difícil comunicarse",
        "nunca pude hablar",
        "hablar con un representante",
        "hablar con una persona",
        "hablar con un humano",
        "quiero hablar con alguien",
        "quiero hablar con una persona real",
        "quiero comunicarme con la mesa de ayuda",
        "no quiero hablar con una máquina",
        "no quiero un bot",
        "chatbot no sirve",
        "respuestas prearmadas",
        "me pasan de número en número",
        "me cortan la comunicación",
        "no permiten dar de baja",
        "no resuelven el problema",
        "me cansé de marcar opciones",
        "opciones que no sirven",
        "la máquina repite lo mismo",
        "todo el tiempo la misma grabación",
        "te hacen esperar",
        "la comunicación es mala",
        "no puedo resolverlo por teléfono",
        "la música en espera",
        "esperando atención",
        "esperando a que atiendan",
        "no puedo hacer el reclamo",
        "me transfieren y no atiende nadie",
        "llamo y me rechazan",
        "no atiende un ser humano",
        "cuesta mucho comunicarse",
        "sin contacto humano",
        "dificultad para hablar",
        "demasiadas vueltas para atención",
        "chatbot no resuelve",
        "nadie atiende los teléfonos",
        "no puedo llegar a un operador",
        "problema con ivr",
        "contestador", "contestadora", 
    ],
    "Tiempos de Atención": [
        "espera de 50 minutos",
        "me dejan colgado",
        "media hora esperando",
        "esperas 3 hs",
        "tardan horas",
        "espera telefónica",
        "esperando con música",
        "esperar mucho",
        "tiempo no vale",
        "esperando por teléfono",
        "imposible poder hablar"
    ],
    "Delivery": [
        "nunca me llegó",
        "no me enviaron",
        "demoras en la entrega",
        "esperando la entrega",
        "no llegó el equipo",
        "no me entregraron",
        "me cobraron y no llegó",
        "fallaron con la venta",
        "compra que nunca me llegó",
        "andreani",
        "entrega de un chip",
        "no enviaron la línea",
    ],
    "Adultos Mayores": [
        "jubilado", "jubilada", "jubilados", "jubiladas",
        "soy jubilado", "soy jubilada",
        "como jubilado", "como jubilada",
        "adulto mayor", "adultos mayores",
        "personas mayores", "gente mayor",
        "edad avanzada",
        "no piensan en los jubilados",
        "no piensan en los adultos mayores",
        "bonificación de jubilado",
        "bonificación de jubilada",
        "sin beneficios para jubilados",
        "no hay descuento para jubilados",
        "precio muy alto para jubilado",
        "muy caro para un jubilado",
        "es carísimo para jubilados",
        "no puedo pagar siendo jubilado",
        "yo no lo puedo pagar, soy jubilado",
        "precio alto para jubilados",
        "no hay beneficios como jubilado",
        "no hay beneficios como jubilada",
        "sin descuento siendo jubilada",
        "no tengo ningún beneficio con la cuota mensual",
        "aumenta pero mi jubilación no",
        "los sueldos no aumentan, yo soy jubilada",
        "no me hacen bonificación de jubilada",
        "soy jubilado con la mínima",
        "mi marido también es jubilado",
        "es difícil para una persona mayor"
    ],
    "Politica Comercial": [
        "promo", "promos", "promoción", "promociones",
        "beneficio", "beneficios", "bonificación", "bonificaciones",
        "descuento", "descuentos", "descontar",
        "aumento mensual", "altos valores", "ley de comunicación",
        "precios", "precio", "valor", "valores",
        "tarifa", "tarifas", "promociones", "promoción",
        "aumento", "aumentos", "aumentan", "aumenta", "incremento", "incrementos",
        "oferta", "ofertas",
        "más caro", "carísimo", "muy caro", "precios elevados",
        "para clientes nuevos", "a los nuevos", "a los usuarios nuevos",
        "no cumplen", "no cumplieron", "no respetan promociones",
        "no me dan las promociones", "me aumentan cada rato",
        "renovación de promociones", "renovar promoción", "renovar promos",
        "cobran más a", "cobran menos a los nuevos", "cobran distinto",
        "política de fidelidad", "fidelidad del cliente",
        "no hay beneficio por antigüedad", "no hay promociones para clientes antiguos",
        "usuarios antiguos pagamos más", "desigualdad en promociones",
        "me dijeron que iba a tener promoción", "ofrecen y no cumplen",
        "me hacen llamar para pedir promoción",
        "tengo que llamar para que me den un descuento",
        "hay que llamar cada 6 meses",
        "caducan rápidamente", "vencen las promociones",
        "No cumplen con lo contratado"
    ],
    "Cliente, No Cliente": [
        "no soy cliente",
        "no tengo personal",
        "no tengo flow"
    ],
    "Funcionamiento del Servicio": [
        "se corta",
        "se tilda",
        "pésima señal", "pesima señal",
        "se corta todo el tiempo",
        "servicio regular",
        "se corta muy seguido",
        "funciona muy mal",
        "funcionando muy mal",
        "cortes", "falla", "fallas", "faya", "fayas",
        "cortes frecuentes",
        "cortes intermitentes",
        "interrupciones",
        "se desconecta",
        "pérdida de señal",
        "la señal va y viene",
        "la señal se cae",
        "la señal se pierde",
        "se cuelga",
        "se cuelga el servicio",
        "servicio colgado",
        "fallas constantes",
        "fallas frecuentes",
        "funciona mal",
        "anda mal",
        "muy mal servicio",
        "pésimo servicio",
        "el servicio es un desastre",
        "no funciona bien",
        "no funciona correctamente",
        "no anda",
        "nunca anda bien",
        "mal funcionamiento",
        "no tengo servicio",
        "sin servicio",
        "no tengo internet",
        "sin conexión",
        "internet se corta",
        "no tengo wifi",
        "no tengo buena señal",
        "la señal es débil",
        "no llega el wifi",
        "no hay cobertura",
        "poca señal",
        "baja señal",
        "alcance limitado",
        "problemas de conexión",
        "problemas de conectividad",
        "problemas con el modem",
        "problemas con el deco",
        "reiniciar el modem",
        "tengo que reiniciar",
        "reinicio constante",
        "hay que reiniciar",
        "el modem no funciona",
        "el deco se tilda",
        "el deco funciona mal",
        "deco tildado",
        "servicio inestable",
        "servicio intermitente",
        "servicio deficiente",
        "servicio lento",
        "velocidad lenta",
        "velocidad baja",
        "muy lento",
        "es lento",
        "internet lento",
        "la velocidad no es la contratada",
        "la velocidad no se cumple",
        "no me dan los megas",
        "poca velocidad",
        "tengo 300 megas y no llegan",
        "nunca llegan los megas",
        "fluctuación de velocidad",
        "la conexión es inestable",
        "la red es inestable",
        "caída del servicio",
        "caídas frecuentes",
        "no resuelven",
        "no mandan técnico",
        "reclamo sin respuesta",
        "no lo solucionan",
        "no viene el técnico",
        "no arreglan",
        "no solucionan",
        "problemas sin resolver",
        "reclamé muchas veces",
        "ya hice reclamos",
        "hice mil reclamos",
        "mala atención técnica",
        "sin solución",
        "atención deficiente",
        "esperando solución",
        "sigo esperando técnico",
        "técnico no vino",
        "no tengo fibra óptica",
        "cableado viejo",
        "todavía tengo cobre",
        "no llega a domicilio",
        "cambio a fibra nunca llega",
        "modem viejo",
        "deco viejo",
        "no tengo buena cobertura",
        "anda pésimo",
        "horrible conexión",
        "malísimo",
        "no puedo trabajar",
        "imposible usar zoom",
        "me quedo sin internet",
        "se corta flow",
        "flow no funciona",
        "flow se tilda",
        "flow se cuelga",
        "mala programación",
        "pixeleo",
        "imagen congelada",
        "imagen se congela",
        "streaming se interrumpe",
        "no puedo ver netflix",
        "series se cortan",
        "no se puede ver nada",
        "se corta la tele",
        "problemas con la TV",
        "se pixela",
        "la imagen se congela",
        "interrupción en youtube",
        "la velocidad no alcanza",
        "internet no llega a toda la casa",
        "wifi no cubre toda la casa",
        "conexión no es",
        "funciona con intermitencia",
    ],
    "Competencia": [
        "Telecentro",
        "Claro",
        "Movistar",
        "iplan",
        "es la unica que hay",
        "empresas", "empresa", "no es mejor que otras"
    ],
    "Adicionales Packs": [
        "packs",
        "paquete", "paquetes",
        "plan futbol", "pack futbol"
    ],
    "Microcortes": [
        "micro corte", "MICRO CORTES",
        "se corta mucho",
        "conexión yendo y viniendo",
        "continuos cortes",
        "desconecciones", "desconexiones", "desconexión", "desconeccion",
        "se entre corta",
        "cortando", "cortandose",
        "cortar",
        "no resolvio el problema",
        "microcortes",
        "interrupciones",
        "inestable",
        "corta y vuelve",
        "el sevicio no es continuo",
        "se corta bastante",
        "se vive cortando",
        "los cortes",
        "hay intermitencias",
        "cortes constantes",
        "se interrumpe",
        "internet se corta",
        "tiene muchos cortes",
    ],
    "Modem": [
        "router viejo",
        "modem viejos",
        "los aparatos",
        "se descompagina"
    ],
    "Outage": [
        "inconveniente en la zona",
        "problema en la zona",
        "horas sin cable ni internet",
    ],
    "Resolución": [
        "no me resolvieron", "no me resolvieon", "no fue resuelto", "no solucionaron", "no solucionan", "no solucionan nada",
        "no solucionan los reclamos", "no solucionan los problemas", "no resuelven", "no resuelven nada", "no resuelven el problema",
        "no me han solucionado", "no me solucionaron", "no me solucionó", "no se resuelve nada", "sin solución", "sin resolver",
        "problema sin resolver", "problemas sin resolver", "nunca lo resolvieron", "no solucionaron el problema",
        "no hay respuesta", "no le dan respuesta", "no responden los reclamos", "falta de solución", "no hay solución",
        "demoras en resolver", "tardan en resolver", "resuelven tarde", "no cumplen", "no cumplieron", "obtener respuesta",
        "reclamos reiterados", "mil vueltas", "muchas vueltas", "dando vueltas", "complicado resolver", "es imposible resolverlo",
        "no me ayudan", "no me ayudaron", "no me atienden", "me cortaron", "me cuelgan", "me cortan", "me pasan de un lado al otro",
        "me transfieren", "me derivan", "no toman en cuenta mi reclamo", "no toman mi reclamo", "no toman mi inconveniente",
        "no cumplen con lo prometido", "me dijeron que", "no cumplen lo que dicen", "me ofrecieron algo y no cumplieron",
        "me dan vueltas", "me siguen facturando", "no se puede dar de baja", "falta de seguimiento",
        "prometieron resolver", "no solucionan nada de lo que pedí", "solución parcial", "resuelto parcialmente",
        "respuesta insatisfactoria", "respuesta parcial", "respuesta tardía", "sin solución definitiva",
        "no recomendaría", "problema sin solución", "problemas que no se resuelven", "servicio estable pero no resuelven",
        "reclamo sin respuesta", "nunca me llamaron", "me siguen reclamando", "me cobraron igual", "no dan respuesta clara",
        "no solucionan", "no te dan soluciones", "solución", "soluciones", "no dan respuesta", "reclamos", "no tiene soporte",
        "no se resuelve"
    ],
    "Atención en la Venta": [
        "contratar",
        "mala experiencia",
        "contraté",
        "lo contratado",
        "no informan bien",
        "comprar",
        "condiciones del abono",
    ],
    "App/Web/whatssApp": [
        "web",
        "app mi personal",
        "la app movil",
        "personal pay",
        "instagram",
        "twitter",
        "canal de whatsapp",
        "whatsapp"
    ],
    "Móvil": [
        "movil", "celular",
        "mi celular"
    ],
    "Retiro Equipos": [
        "retiraron modem", "retiraron el equipo", "devolución de equipos"
    ],
    "Roaming": [
        "roaming"
    ],
    "Robo Cable":[
        "robaron los cables", "los cables"
    ],
    "Sin Servicio": [
        "sin servicio", "no tengo servicio", "no tengo internet", "me cortaron el servicio",
        "me dejaron sin servicio", "no anda el internet", "sin conexión", "no tengo línea",
        "me dejaron sin internet", "me dejaron sin línea", "sin wifi", "no tengo wifi",
        "me desconectaron", "sin teléfono", "sin telefonía", "me sacaron el servicio",
        "me lo cortaron", "cortaron el servicio", "corte de servicio", "no brindan el servicio",
        "no tengo red", "sin red", "no me reconectan", "no lo han arreglado", 
        "hace días sin servicio", "hace semanas sin servicio", "hace meses sin servicio",
        "sin internet hace", "sin línea fija", "desde que me cortaron", "me lo suspendieron",
        "no lo repusieron", "no me lo restablecen", "jamás me reconectaron", 
        "casi un mes sin servicio", "más de un mes sin servicio", "no me reestablecen",
        "no me lo solucionaron", "no me reconectaron", "no me devuelven el servicio",
        "no tengo conexión", "no restablecen la línea", "sin servicio desde",
        "me lo cortaron sin aviso", "no hay servicio", "sin señal de internet",
        "no se reestableció", "me lo quitaron", "sin internet ni teléfono",
        "nos dejaron sin servicio", "jamás volvió el servicio", "no volvió el internet"
],
    "Telefonía Fija": [
        "sin teléfono", "telefono", "teléfono", "telefono fijo",
        "telefonía"
    ]
}

# --- Función para normalizar frases ignorando el orden de las palabras ---
def normalizar_frase(frase):
    palabras = frase.lower().split()
    return " ".join(sorted(palabras))

# --- Diccionario con frases normalizadas (para usar en el tagging) ---
dolores_normalizados = {
    dolor: [normalizar_frase(token) for token in tokens]
    for dolor, tokens in dolores.items()
}