dolores = {
    "Atención al cliente": [
        "asesor",
        "asesoramiento",
        "atención deficiente",
        "atienden sin ganas",
        "call center",
        "complicado dar de baja",
        "demasiadas vueltas para resolver",
        "desatencion",
        "destrato",
        "destrato total",
        "el asesor",
        "el asesor no tenía ganas de  hablar",
        "el cliente no importa",
        "el operador me atendio de mala gana",
        "esperar mucho para una respuesta",
        "falsa promesa",
        "falta de empatía",
        "falta de respeto",
        "falta de seriedad",
        "grito",
        "irrespetuoso",
        "la atencion",
        "la atencion es pesima",
        "la atencion es una porquería",
        "la atencion fue pedante y no resolutiva",
        "la atención",
        "la atención",
        "la baja es difícil",
        "los operadores son  nefastos al momento de explicar",
        "los que atienden",
        "mal educada",
        "mal manejo con los clientes",
        "mal servicio de atención",
        "mala atencion",
        "maltrato",
        "maltrato del empleado",
        "me atendieron mal",
        "me corto",
        "me mintieron",
        "me pasean de un área a otra",
        "me trataron",
        "no ayudan al cliente",
        "no brindan soluciones",
        "no cuidan al cliente",
        "no escuchan",
        "no explican bien",
        "No les interesa el cliente",
        "no me atiende",
        "no me escucho",
        "no me llamaron",
        "no me solucionan nada",
        "no solucionan los errores que cometen",
        "nunca responden los reclamos",
        "operador",
        "operadora",
        "pesima atencion",
        "pesima atencion",
        "pesima gestion atención telefonica",
        "poca claridad",
        "poco cortez",
        "prometieron llamarme y no lo hicieron",
        "pésima atención",
        "rapida respuesta",
        "reclamo",
        "representantes soberbios y maleducados",
        "respeto al cliente",
        "respuesta rapida",
        "se ríe",
        "sin soluciones claras",
    ],
    "Alerta Match": [
        "fue grosero",
        "me faltó el respeto",
        "me gritó",
        "me maltrataron",
        "me respondió mal",
        "me trataron",
        "me trató mal",
        "pedante",
        "soberbio",
        "trato agresivo",
        "trato inaceptable",
    ],
    "Encuesta": [
        "comentarios",
        "derivar a mensajes",
        "encuestas",
        "LA ENCUESTA",
        "solicitudes",
    ],
    "Cadom": [
        "cambio de domicilio",
        "me mude",
        "mudanza",
    ],
    "Catit": [
        "cambiar la titularidad",
        "cambio de titularidad",
        "el titular",
        "titularidad",
    ],
    "Catec": [
        "cambiar el equipo",
        "cambio de modem",
        "cambio de servicio no solicitado",
        "cambio del modem",
        "la nueva tecnlogia",
        "menos señal desde el cambio",
        "modem viejo",
        "módem",
        "problemas con el cambio de tecnología",
        "problemas técnicos tras el cambio",
    ],
    "Cobertura": [
        "cobertura",
        "no cubre",
        "no hay cobertura",
        "no tengo buena cobertura",
        "no tengo cobertura",
    ],
    "Conveniencia": [
        "anda mal y es caro",
        "atencion al cliente",
        "cada vez más caro y peor",
        "carisimo el servicio",
        "caro y se corta siempre",
        "cobra mucho y no anda",
        "cobran una fortuna",
        "costo y servicio",
        "deficiente servicio",
        "el mas caro del mercado",
        "el servicio",
        "el servicio no lo vale",
        "elevado y calidad mal",
        "está muy caro el servicio",
        "mal funcionamiento y precio alto",
        "mal servicio por el precio",
        "mal servicio y se corta",
        "mala calidad por precio",
        "malisimo servicio y atencioncada vez más caro",
        "muy cara y se corta",
        "muy caro para lo que brindan",
        "muy caro y funciona mal",
        "muy costoso y anda mal",
        "no confiable",
        "no es tan bueno",
        "no funciona",
        "no funciona y es muy caro",
        "no hay relacion precio calidad",
        "no recomendar",
        "pago mucho y funciona mal",
        "pobre servicio",
        "precio alto y servicio deficiente",
        "precio elevado por mala calidad",
        "precio excesivo por lo que ofrecen",
        "producto calidad",
        "relacion costo servicio",
        "relación precio calidad pésima",
        "se corta y es caro",
        "se descompone",
        "servicio malo y caro",
        "servicio muy caro",
        "sin comunicación",
        "sin internet",
    ],
    "Baja del Servicio": [
        "baja del servicio",
        "baja el servicio",
        "dar de baja",
        "di de baja",
        "dio de baja",
        "gestione baja",
        "la baja",
        "no dan de baja",
        "no permiten dar de baja",
        "pedi la baja",
        "se le dio de baja",
        "solicitar la baja",
    ],
    "Cobre": [
        "banda ancha",
        "barrio",
        "cable de cobre",
        "cobre",
        "digitalizacion",
        "digitalizaron",
        "mega",
        "megas",
        "no llega a mi barrio",
        "poco alcance",
        "todavía tengo cobre",
    ],
    "Quiero Fibra": [
        "a mi zona todavía no llega la fibra",
        "años esperando fibra óptica",
        "aún no tengo fibra",
        "banda ancha inexistente",
        "cableado viejo",
        "cambio a fibra nunca llega",
        "cambio de tecnología a fibra óptica",
        "cambio de tecnología y no tengo fibra",
        "desde que me pasaron a fibra",
        "esperando la reconversión a fibra óptica",
        "esperando la solución para pasarme a fibra",
        "esperando que llegue la fibra",
        "estaría bárbaro que traigan fibra óptica",
        "estoy con el cable de cobre",
        "estoy esperando fibra óptica",
        "están cambiando a fibra pero no llegó",
        "fibra",
        "fibra en la zona",
        "fibra no funciona bien",
        "fibra optica",
        "hasta que no pongan fibra óptica",
        "me cambiaron a fibra y funciona peor",
        "me dijeron que iban a instalar fibra y no lo hicieron",
        "me prometieron fibra óptica",
        "mi línea está en migración",
        "navego con 3 megas",
        "no extendieron la red de fibra óptica",
        "no funciona el servicio por cable",
        "no hay conexión con fibra óptica",
        "no invierten en poner fibra óptica",
        "no llega a domicilio",
        "no llegó fibra óptica",
        "no me ofrecen fibra óptica",
        "no pueden ofrecerme fibra",
        "no puedo disponer de fibra óptica",
        "no quieren colocarme fibra",
        "no saben cuándo llega la fibra",
        "no tengo banda ancha",
        "no tengo fibra óptica",
        "no tengo fibra óptica",
        "nunca vinieron a colocar la fibra óptica",
        "problemas con la instalación de fibra",
        "problemas por cambiar a fibra óptica",
        "prometieron fibra y nunca llegó",
        "publicitan fibra óptica pero no llega",
        "solo cuento con 6 megas",
        "solo tengo 2 megas",
        "solo tengo par de cobre",
        "tengo apenas 10 megas",
        "tengo que esperar a que pase la fibra óptica",
        "todavía tengo cobre",
        "zona de migración",
    ],
    "Velocidad": [
        "300 megas",
        "anda muy lenta",
        "anda muy lentano es rapida",
        "anda muy lento",
        "baja velocidad de bajada",
        "conexion deficiente",
        "conexion lenta",
        "falta velocidad",
        "funciona lento",
        "la velocidad de internet",
        "lenta",
        "lentitud",
        "lento",
        "lerda",
        "lerdo",
        "llegan pocos megas",
        "muy baja velocidad",
        "muy lento",
        "Muy lento el Internet",
        "muy lerdo",
        "no es muy rapida",
        "no hay velocidad",
        "rapida",
        "tarda muchisimo",
        "velocidad",
        "velocidad baja",
        "velocidad inestable",
        "veloz",
    ],
    "Precio": [
        "abono elevado",
        "abono mensual",
        "abono muy caro",
        "ajustes mensuales",
        "alta factura",
        "aumenta el precio",
        "aumenta todos los meses",
        "aumentan sin avisar",
        "aumento de precio",
        "aumentos",
        "aumentos constantes",
        "cada mes más caro",
        "cada vez más caro",
        "cara",
        "carisimo",
        "caro",
        "carísima",
        "carísimo",
        "comparación con otras",
        "comparado con otras",
        "costo",
        "costo altísimo",
        "costo elevado",
        "costo muy alto",
        "costo muy elevado",
        "costo-beneficio",
        "costos",
        "costos elevados",
        "costosa",
        "costoso",
        "cuesta mucho",
        "demaciado caro",
        "demasiado cara",
        "demasiado caro",
        "demasido caro",
        "difícil de pagar",
        "es cara",
        "es caro",
        "es carísimo",
        "es muy caro",
        "es muy costoso",
        "es una estafa",
        "está muy cara",
        "está muy caro",
        "exageradamente caro",
        "excesivamente caro",
        "excesivamente costoso",
        "factura elevada",
        "hay opciones más baratas",
        "impagable",
        "imposible de pagar",
        "incremento de precio",
        "inflación",
        "injustificado",
        "lo subieron",
        "me aumentan",
        "me aumentaron",
        "me cobran",
        "me subieron",
        "monto altísimo",
        "monto elevado",
        "monto elevado",
        "muy cara",
        "muy caro",
        "muy costosa",
        "muy costoso",
        "más barato en otro lado",
        "más caro que",
        "no lo puedo pagar",
        "no se justifica el gasto",
        "no se justifica lo que cobran",
        "pagando",
        "pago mucho",
        "pesio",
        "precio",
        "precio alto",
        "precio del servicio",
        "precio elevado",
        "precio excesivo",
        "precios",
        "presio",
        "presios",
        "relación costo",
        "relación precio",
        "sin previo aviso",
        "suba",
        "suba de precio",
        "subas",
        "subas constantes",
        "suben",
        "suben el precio",
        "subida de precio",
        "subieron",
        "subió el precio",
        "tarifa",
        "tarifa alta",
        "tarifa elevada",
        "tarifa mensual",
        "valor de la tarifa",
        "valor del abono",
        "valor excesivo",
        "valores altos",
        "ya no puedo pagarlo",
    ],
    "Aviso Mora": [
        "aviso de deuda",
        "cartel de corte",
        "cobran",
        "cobranzas",
        "cobro",
        "debo",
        "deuda",
        "deudas",
        "deudor",
        "factura no corresponde",
        "no debo",
        "reclamos por deuda",
        "se atrasa dias",
        "sistema de cobro",
    ],
    "Facturación": [
        "cambio de",
        "cobran",
        "cobran lo que quieren",
        "cobraron",
        "cobros automáticos no autorizados",
        "cobros inesperados",
        "cuota",
        "cuota mensual",
        "cuotas",
        "dan de alta servicios que no se piden",
        "dar de",
        "debitaron",
        "debito automatico",
        "desastres en la facturación",
        "descuento aplicado y luego cobrado igual",
        "descuento nunca aplicado",
        "desorden en la facturación",
        "duplican la facturación",
        "error de facturación",
        "error en facturación",
        "errores sistemáticos en facturación",
        "factura",
        "factura errónea",
        "factura vencida",
        "facturacion",
        "facturación confusa",
        "facturación desastrosa",
        "facturan",
        "facturan lo que quieren",
        "facturan servicios no contratados",
        "facturando",
        "facturas",
        "falta de bonificación",
        "historial",
        "importe de la factura",
        "intereses",
        "me cobran anticipado",
        "me cobran cosas que no pedí",
        "me cobran de más todos los meses",
        "me cobran servicios que no contraté",
        "me cobran sin tener el servicio",
        "me cobraron dos veces",
        "me están reclamando",
        "me siguen cobrando",
        "montos que no reconozco",
        "no cumplen lo pactado",
        "no cumplen lo prometido",
        "no hacen el descuento",
        "no puedo acceder a la factura",
        "no respetan lo pactado",
        "no respetan precios",
        "no respetan promociones",
        "notificacion",
        "nunca recibí el descuento",
        "nunca respetan el precio acordado",
        "precio del abono",
        "precio distinto al promocionado",
        "problemas constantes con las facturas",
        "problemas para ver la factura",
        "promo sin descuento",
        "reclamo constante de facturación",
        "reclamo de deuda",
        "vencimiento",
    ],
    "Indefinido": [
        "",
        " ",
        ".",
        "..",
        "...",
        "....",
        ".....",
        "0",
        "1",
        "10",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "buena",
        "buena.",
        "bueno",
        "bueno.",
        "conforme",
        "eficaz",
        "es mi verdad",
        "horrible",
        "ineficientes",
        "ineptos",
        "mal serv8cio",
        "me coetaron",
        "mexes util",
        "nada",
        "nan",
        "ninguna",
        "no dan",
        "no entiendo que puse",
        "no hay",
        "no me",
        "no pt",
        "no tengo",
        "none",
        "ok",
        "pedorro",
        "pesimo el wifr",
        "po",
        "por",
        "porque sí",
        "pq",
        "pt",
        "pésima señal",
        "pésimo",
        "q no es tannnn bueno cm parecia",
        "simplemete x la atenxion",
        "sin palabras",
        "todos a quien conozco tienen personal",
        "un desastre",
        "xq",
    ],
    "Pasivos": [
        "anda bien",
        "brindan buen servicio",
        "buen servicio bien la velocidad",
        "buen servicio pero",
        "buena conexión en general",
        "buena señal",
        "casi nunca tiene contratiempos",
        "considero que es el término normal",
        "es aceptable",
        "es recomendable",
        "está bien pero no es la gran cosa",
        "ninguno. todo bien",
        "no he tenido inconvenientes significativos",
        "no respetaron un acuerdo pero buen servicio",
        "que se tiene buena señal",
        "todo bien",
    ],
    "Pagos": [
        "cobran mora",
        "cobro antes del vencimiento",
        "confusa la posibilidad de abonar",
        "debito automático",
        "descuentan cuando quieren",
        "gestión de pago",
        "homebanking",
        "no logro pagar",
        "no puedo pagar",
        "no puedo pagar con débito",
        "no se puede pagar",
        "no sé cómo efectuar el pago",
        "pagar",
        "pago",
        "pago virtual",
        "pago virtual y rápida",
        "problemas para pagar",
        "servicio limitado por falta de pago",
        "tarjeta de credito",
        "visa",
    ],
    "Atención Sucursal": [
        "abasto",
        "belgrano",
        "en cabildo",
        "oficina",
        "oficina de honduras",
    ],
    "Atención Técnico": [
        "cita",
        "demora",
        "demora",
        "el servicio tecnico",
        "el técnico",
        "fallas en la instalación",
        "fue el tecnico",
        "inconveniente técnico",
        "instalacion",
        "instalacion precaria",
        "irresponsables",
        "la instalación no se completó",
        "los técnicos",
        "mal servicio tecnico",
        "no hay soporte",
        "no la instalaron",
        "no me lo instalan",
        "no me pusieron",
        "no pudieron instalarlo",
        "no pudieron terminar",
        "no se realizó ningún trabajo",
        "no vino el",
        "poco calificado",
        "problema técnico",
        "problemas cable",
        "reparaciones",
        "reparación",
        "servicio tecnico",
        "servicio tecnico deficiente",
        "servicio técnico",
        "solicitar un tecnico",
        "tardaron",
        "tecnica",
        "turno",
        "vino el tecnico",
    ],
    "Cita Técnica": [
        "agendado",
        "bot avisó horas más tarde",
        "cancelaron la visita",
        "cita reprogramada sin aviso",
        "el equipo de agendamiento es un desastre",
        "esperé toda la mañana",
        "esperé y no vinieron",
        "fallaron en la instalación",
        "fueron a otro domicilio",
        "incumplieron la visita técnica",
        "me dejaron esperando",
        "me dejaron plantada",
        "me dejaron plantado",
        "me dieron turno y no vinieron",
        "me dijeron que reagende",
        "me hicieron esperar todo el día",
        "nadie vino",
        "no apareció el técnico",
        "no cumplieron con la cita",
        "no cumplieron con la visita",
        "no mandan técnico",
        "no me avisaron",
        "no se presentó el técnico",
        "no viene el técnico",
        "no vienen",
        "no vinieron",
        "no vino",
        "no vino el técnico",
        "no vino nadie al domicilio",
        "nunca hicieron la instalación",
        "nunca me lo instalaron",
        "prometen venir",
        "prometieron día y hora",
        "prometieron venir y no vinieron",
        "prometieron visita que no ocurrió",
        "sigo esperando técnico",
        "turno no cumplido",
        "técnico no vino",
        "técnico nunca vino",
        "visita",
        "visita técnica incumplida",
        "visitas pactadasni siquiera aparecieron",
        "visitas técnicas",
    ],
    "Flow": [
        "aplicacion",
        "aplicacion flow",
        "app",
        "app flow",
        "cambian horarios de series",
        "cambio de deco",
        "cambio de decodificador",
        "canal pago",
        "canales",
        "canales no se ven",
        "canales que no se ven",
        "codifcadores",
        "codificador",
        "contenido desactualizado",
        "contenido ya emitido",
        "control remoto",
        "deco tildado",
        "deco viejo",
        "deco viejo",
        "decodificador",
        "decodificador",
        "decodificadores",
        "decodificadores",
        "el deco funciona mal",
        "el deco se tilda",
        "flow",
        "flow no funciona",
        "flow se cuelga",
        "flow se tilda",
        "grilla",
        "guia",
        "imagen",
        "imagen congelada",
        "imagen se congela",
        "mala programación",
        "nitidez",
        "no funciona el control remoto",
        "no funciona flow",
        "no puedo ver",
        "no puedo ver programas anteriores",
        "no se conecta flow",
        "no se usar flow",
        "no tengo flow",
        "no tiene subtítulos",
        "nunca pude habilitar flow",
        "pelicula",
        "películas viejas",
        "pixeleo",
        "problemas con el deco",
        "problemas con el deco",
        "problemas con la app de flow",
        "problemas con la TV",
        "problemas para loguearme",
        "programación caduca",
        "programas repetidos",
        "repetición de capítulos",
        "repetición de programas",
        "sacaron canales",
        "se corta flow",
        "se pixela",
        "streaming",
        "television",
        "todo nublado",
        "TV",
        "tv",
    ],
    "IVR": [
        "20 horas para que atiendan",
        "atención automática",
        "atención no personalizada",
        "atiende siempre una máquina",
        "atiende un contestador",
        "chatbot no resuelve",
        "chatbot no sirve",
        "contacto con la empresa",
        "contestador",
        "contestadora",
        "cuesta mucho comunicarse",
        "demasiadas vueltas para atención",
        "demora para hablar",
        "dificil comunicarse",
        "dificultad para hablar",
        "es difícil comunicarse",
        "es muy difícil comunicarse",
        "espera eterna",
        "espera larga",
        "esperando a que atiendan",
        "esperando atención",
        "esperar mucho",
        "falta de atencion",
        "habla una grabación",
        "hablar con un humano",
        "hablar con un humano",
        "hablar con un representante",
        "hablar con una persona",
        "imposible comunicarse",
        "imposible comunicarse con un operador",
        "imposible hablar",
        "la comunicación es mala",
        "la máquina repite lo mismo",
        "la música en espera",
        "llamo y me rechazan",
        "llamás y nadie atiende",
        "llamás y no atienden",
        "llamé 6 veces y nadie atiende",
        "llamé muchas veces y nada",
        "llamé varias veces y no se comunicaron",
        "me atiende una máquina",
        "me cansé de marcar opciones",
        "me contesta una máquina",
        "me cortan la comunicación",
        "me pasan de número en número",
        "me pasaron con un contestador automático",
        "me ponene en espera",
        "me transfieren y no atiende nadie",
        "menú automático",
        "muchas opciones",
        "nadie atiende",
        "nadie atiende los teléfonos",
        "nadie contesta",
        "nadie me atiende",
        "nadie responde",
        "no atiende un ser humano",
        "no atienden",
        "no contestan",
        "no dan la opción",
        "no dispongo contacto con operador",
        "no existe la opción",
        "no hay atención",
        "no hay con quién hablar",
        "no hay forma de hablar con alguien",
        "no hay opción",
        "no me atendieron",
        "no me atienden",
        "no me dan la opción que necesito",
        "no me puedo comunicar",
        "no permiten dar de baja",
        "no puedo comunicarme",
        "no puedo hacer el reclamo",
        "no puedo resolverlo por teléfono",
        "no quiero hablar con una máquina",
        "no quiero un bot",
        "no te atiende nadie",
        "nunca contesta una persona",
        "nunca me atienden",
        "nunca pude hablar",
        "opciones infinitas",
        "opciones que no sirven",
        "problema con ivr",
        "problema con ivr",
        "quiero comunicarme con la mesa de ayuda",
        "quiero hablar con alguien",
        "quiero hablar con una persona real",
        "respuestas prearmadas",
        "sin atención",
        "sin contacto humano",
        "sistema automático",
        "solo atiende un robot",
        "sólo atiende una computadora",
        "tardan en atender",
        "te hacen esperar",
        "todo el tiempo la misma grabación",
    ],
    "Tiempos de Atención": [
        "espera de 50 minutos",
        "espera telefónica",
        "esperando con música",
        "esperando por teléfono",
        "esperar mucho",
        "esperas 3 hs",
        "imposible poder hablar",
        "me cortan",
        "me cortaron",
        "me cuelgan",
        "me dejan colgado",
        "me derivan",
        "me pasan de un lado al otro",
        "me transfieren",
        "media hora esperando",
        "no me atienden",
        "no puedo llegar a un operador",
        "tardan horas",
        "tiempo no vale",
    ],
    "Adultos Mayores": [
        "adulto mayor",
        "adultos mayores",
        "aumenta pero mi jubilación no",
        "bonificación de jubilada",
        "bonificación de jubilado",
        "como jubilada",
        "como jubilado",
        "edad avanzada",
        "es carísimo para jubilados",
        "es difícil para una persona mayor",
        "gente mayor",
        "jubilada",
        "jubiladas",
        "jubilado",
        "jubilados",
        "los sueldos no aumentan, yo soy jubilada",
        "mi marido también es jubilado",
        "muy caro para un jubilado",
        "no hay beneficios como jubilada",
        "no hay beneficios como jubilado",
        "no hay descuento para jubilados",
        "no me hacen bonificación de jubilada",
        "no piensan en los adultos mayores",
        "no piensan en los jubilados",
        "no puedo pagar siendo jubilado",
        "no tengo ningún beneficio con la cuota mensual",
        "personas mayores",
        "precio alto para jubilados",
        "precio muy alto para jubilado",
        "sin beneficios para jubilados",
        "sin descuento siendo jubilada",
        "soy jubilada",
        "soy jubilado",
        "soy jubilado con la mínima",
        "yo no lo puedo pagar, soy jubilado",
    ],
    "Politica Comercial": [
        "a los nuevos",
        "a los usuarios nuevos",
        "altos valores",
        "aumenta",
        "aumentan",
        "aumento",
        "aumento mensual",
        "aumentos",
        "beneficio",
        "beneficios",
        "bonificaciones",
        "bonificación",
        "caducan rápidamente",
        "carísimo",
        "cobran distinto",
        "cobran menos a los nuevos",
        "cobran más a",
        "descontar",
        "descuento",
        "descuentos",
        "desigualdad en promociones",
        "fidelidad del cliente",
        "hay que llamar cada 6 meses",
        "incremento",
        "incrementos",
        "ley de comunicación",
        "me aumentan cada rato",
        "me dijeron que iba a tener promoción",
        "me hacen llamar para pedir promoción",
        "muy caro",
        "más caro",
        "no cumplen",
        "No cumplen con lo contratado",
        "no cumplieron",
        "no hay beneficio por antigüedad",
        "no hay promociones para clientes antiguos",
        "no me dan las promociones",
        "no respetan promociones",
        "oferta",
        "ofertas",
        "ofrecen y no cumplen",
        "para clientes nuevos",
        "política de fidelidad",
        "precio",
        "precios",
        "precios elevados",
        "promo",
        "promociones",
        "promociones",
        "promoción",
        "promoción",
        "promos",
        "renovación de promociones",
        "renovar promoción",
        "renovar promos",
        "tarifa",
        "tarifas",
        "tengo que llamar para que me den un descuento",
        "usuarios antiguos pagamos más",
        "valor",
        "valores",
        "vencen las promociones",
    ],
    "Funcionamiento del Servicio": [
        "a veces se corta",
        "alcance limitado",
        "anda mal",
        "anda pésimo",
        "atención deficiente",
        "baja señal",
        "cableado viejo",
        "cambios que afectaron el servicio",
        "caída del servicio",
        "caídas frecuentes",
        "conexión no es",
        "cortes",
        "el modem no funciona",
        "el servicio es un desastre",
        "es lento",
        "esperando solución",
        "falla",
        "fallas",
        "fallas constantes",
        "fallas frecuentes",
        "faya",
        "fayas",
        "fluctuación de velocidad",
        "funciona con intermitencia",
        "funciona mal",
        "funciona muy mal",
        "funcionando muy mal",
        "hay que reiniciar",
        "hice mil reclamos",
        "horrible conexión",
        "imposible usar zoom",
        "internet lento",
        "internet no llega a toda la casa",
        "internet se corta",
        "interrupciones",
        "interrupción en youtube",
        "la conexión es inestable",
        "la red es inestable",
        "la señal es débil",
        "la señal es peor desde que cambiaron",
        "la señal se cae",
        "la señal se pierde",
        "la señal va y viene",
        "la velocidad no alcanza",
        "la velocidad no es la contratada",
        "la velocidad no se cumple",
        "mal funcionamiento",
        "malísimo",
        "me quedo sin internet",
        "muy lento",
        "muy mal servicio",
        "no anda",
        "no arreglan",
        "no funciona bien",
        "no funciona correctamente",
        "no llega a domicilio",
        "no llega el wifi",
        "no lo solucionan",
        "no me dan los megas",
        "no puedo trabajar",
        "no puedo ver netflix",
        "no se puede ver nada",
        "no solucionan",
        "no tengo buena señal",
        "no tengo internet",
        "no tengo servicio",
        "no tengo wifi",
        "nunca anda bien",
        "nunca llegan los megas",
        "pesima señal",
        "poca señal",
        "poca velocidad",
        "problemas con el modem",
        "problemas de conectividad",
        "problemas de conexión",
        "problemas sin resolver",
        "pérdida de señal",
        "pésima señal",
        "pésimo servicio",
        "reclamo sin respuesta",
        "reclamé muchas veces",
        "reiniciar el modem",
        "reinicio constante",
        "se corta",
        "se corta la tele",
        "se corta muy seguido",
        "se corta todo el tiempo",
        "se cuelga",
        "se cuelga el servicio",
        "se desconecta",
        "se tilda",
        "series se cortan",
        "servicio colgado",
        "servicio deficiente",
        "servicio inestable",
        "servicio intermitente",
        "servicio lento",
        "servicio regular",
        "sin conexión",
        "sin servicio",
        "sin solución",
        "streaming se interrumpe",
        "tengo 300 megas y no llegan",
        "tengo que reiniciar",
        "velocidad baja",
        "velocidad lenta",
        "wifi no cubre toda la casa",
        "ya hice reclamos",
    ],
    "Microcortes": [
        "conexión yendo y viniendo",
        "continuos cortes",
        "corta y vuelve",
        "cortando",
        "cortandose",
        "cortar",
        "cortes constantes",
        "cortes frecuentes",
        "cortes intermitentes",
        "desconeccion",
        "desconecciones",
        "desconexiones",
        "desconexión",
        "el sevicio no es continuo",
        "hay intermitencias",
        "inestable",
        "internet se corta",
        "interrupciones",
        "los cortes",
        "micro corte",
        "MICRO CORTES",
        "microcortes",
        "no resolvio el problema",
        "se corta bastante",
        "se corta mucho",
        "se entre corta",
        "se interrumpe",
        "se vive cortando",
        "tiene muchos cortes",
    ],
    "Resolución": [
        "complicado resolver",
        "dando vueltas",
        "demoras en resolver",
        "es imposible resolverlo",
        "falta de seguimiento",
        "falta de solución",
        "me cobraron igual",
        "me dan vueltas",
        "me dijeron que",
        "me ofrecieron algo y no cumplieron",
        "me siguen reclamando",
        "mil vueltas",
        "muchas vueltas",
        "no cumplen",
        "no cumplen con lo prometido",
        "no cumplen lo que dicen",
        "no cumplieron",
        "no dan respuesta",
        "no dan respuesta clara",
        "no fue resuelto",
        "no hay respuesta",
        "no hay solución",
        "no le dan respuesta",
        "no me ayudan",
        "no me ayudaron",
        "no me han solucionado",
        "no me resolvieron",
        "no me solucionaron",
        "no me solucionó",
        "no recomendaría",
        "no responden los reclamos",
        "no resuelven",
        "no resuelven el problema",
        "no resuelven nada",
        "no se resuelve",
        "no se resuelve nada",
        "no solucionan",
        "no solucionan",
        "no solucionan los problemas",
        "no solucionan los reclamos",
        "no solucionan nada",
        "no solucionan nada de lo que pedí",
        "no solucionaron",
        "no solucionaron el problema",
        "no te dan soluciones",
        "no tiene soporte",
        "no toman en cuenta mi reclamo",
        "no toman mi inconveniente",
        "no toman mi reclamo",
        "nunca lo resolvieron",
        "nunca me llamaron",
        "obtener respuesta",
        "problema sin resolver",
        "problema sin solución",
        "problemas que no se resuelven",
        "problemas sin resolver",
        "prometieron resolver",
        "reclamo sin respuesta",
        "reclamos",
        "reclamos reiterados",
        "respuesta insatisfactoria",
        "respuesta parcial",
        "respuesta tardía",
        "resuelto parcialmente",
        "resuelven tarde",
        "servicio estable pero no resuelven",
        "sin resolver",
        "sin solución",
        "sin solución definitiva",
        "soluciones",
        "solución",
        "solución parcial",
        "tardan en resolver",
    ],
    "Atención en la Venta": [
        "comprar",
        "condiciones del abono",
        "contratar",
        "contraté",
        "lo contratado",
        "mala experiencia",
        "no informan bien",
    ],
    "App Web WhatssApp": [
        "app mi personal",
        "canal de whatsapp",
        "instagram",
        "la app movil",
        "personal pay",
        "twitter",
        "web",
        "whatsapp",
    ],
    "Móvil": [
        "celular",
        "mi celular",
        "movil",
    ],
    "Retiro Equipos": [
        "devolución de equipos",
        "retiraron el equipo",
        "retiraron modem",
    ],
    "Sin Servicio": [
        "casi un mes sin servicio",
        "cortaron el servicio",
        "corte de servicio",
        "desde que me cortaron",
        "hace días sin servicio",
        "hace meses sin servicio",
        "hace semanas sin servicio",
        "jamás me reconectaron",
        "jamás volvió el servicio",
        "me cortaron el servicio",
        "me dejaron sin internet",
        "me dejaron sin línea",
        "me dejaron sin servicio",
        "me desconectaron",
        "me lo cortaron",
        "me lo cortaron sin aviso",
        "me lo quitaron",
        "me lo suspendieron",
        "me sacaron el servicio",
        "más de un mes sin servicio",
        "no anda el internet",
        "no brindan el servicio",
        "no hay servicio",
        "no lo han arreglado",
        "no lo repusieron",
        "no me devuelven el servicio",
        "no me lo restablecen",
        "no me lo solucionaron",
        "no me reconectan",
        "no me reconectaron",
        "no me reestablecen",
        "no restablecen la línea",
        "no se reestableció",
        "no tengo conexión",
        "no tengo internet",
        "no tengo línea",
        "no tengo red",
        "no tengo servicio",
        "no tengo wifi",
        "no volvió el internet",
        "nos dejaron sin servicio",
        "sin conexión",
        "sin internet hace",
        "sin internet ni teléfono",
        "sin línea fija",
        "sin red",
        "sin servicio",
        "sin servicio desde",
        "sin señal de internet",
        "sin telefonía",
        "sin teléfono",
        "sin wifi",
    ],
    "Telefonía Fija": [
        "sin teléfono",
        "telefono",
        "telefono fijo",
        "telefonía",
        "teléfono",
    ]    
}

# --- Función para normalizar frases ignorando el orden de las palabras ---
def normalizar_frase(frase):
    palabras = frase.lower().split()
    return " ".join(sorted(palabras))

# --- Diccionario con frases normalizadas (para usar en el tagging) ---
dolores_normalizados = {
    dolor: [normalizar_frase(token) for token in tokens]
    for dolor, tokens in dolores.items()
}