dolores = {
    "Atención al cliente": [
        "asesor",
        "asesoramiento",
        "atención deficiente",
        "atienden sin ganas",
        "call center",
        "complicado dar de baja",
        "demasiadas vueltas para resolver",
        "desatencion",
        "destrato",
        "destrato total",
        "el equipo de agendamiento es un desastre",
        "el asesor",
        "el asesor no tenía ganas de  hablar",
        "el cliente no importa",
        "el operador me atendio de mala gana",
        "esperar mucho para una respuesta",
        "falsa promesa",
        "falta de empatía",
        "falta de respeto",
        "falta de seriedad",
        "grito",
        "irrespetuoso",
        "la atencion",
        "la atencion es pesima",
        "la atencion es una porquería",
        "la atencion fue pedante y no resolutiva",
        "la atención",
        "la atención",
        "la baja es difícil",
        "los operadores son  nefastos al momento de explicar",
        "los que atienden",
        "mal educada",
        "mal manejo con los clientes",
        "mal servicio de atención",
        "mala atencion",
        "maltrato",
        "maltrato del empleado",
        "me atendieron mal",
        "me corto",
        "me mintieron",
        "me pasean de un área a otra",
        "me trataron",
        "no ayudan al cliente",
        "no brindan soluciones",
        "no cuidan al cliente",
        "no escuchan",
        "no explican bien",
        "No les interesa el cliente",
        "no me atiende",
        "no me escucho",
        "no me llamaron",
        "no me solucionan nada",
        "no solucionan los errores que cometen",
        "nunca responden los reclamos",
        "operador",
        "operadora",
        "pesima atencion",
        "pesima atencion",
        "pesima gestion atención telefonica",
        "poca claridad",
        "poco cortez",
        "prometieron llamarme y no lo hicieron",
        "pésima atención",
        "rapida respuesta",
        "reclamo",
        "representantes soberbios y maleducados",
        "respeto al cliente",
        "respuesta rapida",
        "se ríe",
        "sin soluciones claras",
    ],
    "Alerta Match": [
        "fue grosero",
        "me faltó el respeto",
        "me gritó",
        "me maltrataron",
        "me respondió mal",
        "me trataron",
        "me trató mal",
        "pedante",
        "soberbio",
        "trato agresivo",
        "trato inaceptable",
    ],
    "Encuesta": [
        "comentarios",
        "derivar a mensajes",
        "encuestas",
        "LA ENCUESTA",
        "solicitudes",
    ],
    "Cadom": [
        "cambio de domicilio",
        "me mude",
        "mudanza",
    ],
    "Catit": [
        "cambiar la titularidad",
        "cambio de titularidad",
        "el titular",
        "titularidad",
    ],
    "Catec": [
        "me dijeron que iban a instalar fibra y no lo hicieron",
        "problemas con la instalación de fibra",
        "desde que me pasaron a fibra",
        "me cambiaron a fibra y funciona peor",
        "nunca vinieron a colocar la fibra óptica",
        "problemas por cambiar a fibra óptica",
        "cambio de tecnología a fibra óptica",
        "sistema por fibra",
        "cambiaron a fibra",        
        "ponerme fibra",
        "cambiar a fibra",
        "cambio de fibra no funciona",
        "la fibra empeoro la señal"
    ],
    "Cobertura": [
        "cobertura",
        "no cubre",
        "no hay cobertura",
        "no tengo buena cobertura",
        "no tengo cobertura",
    ],
    "Conveniencia": [
        "no hay relacion precio calidad",
        "producto calidad",
        "elevado y calidad mal",
        "relacion costo servicio",
        "muy cara y se corta",
        "no funciona y es muy caro",
        "servicio malo y caro",
        "mal servicio y se corta",
        "costo y servicio",
        "malisimo servicio y cada vez más caro",
        "muy caro y funciona mal",
        "precio excesivo por lo que ofrecen",
        "relación precio calidad pésima",
        "el servicio no lo vale",
        "pago mucho y funciona mal",
        "precio elevado por mala calidad",
        "anda mal y es caro",
        "muy caro para lo que brindan",
        "muy costoso y anda mal",
        "mala calidad por precio",
        "se corta y es caro",
        "caro y se corta siempre",
        "mal funcionamiento y precio alto",
        "precio alto y servicio deficiente",
        "cobra mucho y no anda",
        "mal servicio por el precio",
        "está muy caro el servicio",
        "cada vez más caro y peor"
    ],
    "Baja del Servicio": [
        "baja del servicio",
        "baja el servicio",
        "dar de baja",
        "di de baja",
        "dio de baja",
        "gestione baja",
        "la baja",
        "no dan de baja",
        "no permiten dar de baja",
        "pedi la baja",
        "se le dio de baja",
        "solicitar la baja",
    ],
    "Cobre": [
        "cobre",
        "banda ancha inexistente",
        "solo tengo 2 megas",
        "cable de cobre",
        "todavía tengo cobre",
        "solo cuento con 6 megas",
        "tengo apenas 10 megas",
        "navego con 3 megas"
    ],
    "Quiero Fibra": [
        "no tengo fibra óptica",
        "no tengo banda ancha",
        "aún no tengo fibra",
        "fibra en la zona",
        "fibra no funciona bien",
        "a mi zona todavía no llega la fibra",
        "no extendieron la red de fibra óptica",
        "no hay conexión con fibra óptica",
        "no llegó fibra óptica",
        "esperando que llegue la fibra",
        "estoy esperando fibra óptica",
        "años esperando fibra óptica",
        "hasta que no pongan fibra óptica",
        "no quieren colocarme fibra",
        "no me ofrecen fibra óptica",
        "no invierten en poner fibra óptica",
        "publicitan fibra óptica pero no llega",
        "solo tengo par de cobre",
        "estoy con el cable de cobre",
        "no pueden ofrecerme fibra"
    ],
    "Velocidad": [
        "300 megas",
        "anda muy lenta",
        "anda muy lentano es rapida",
        "anda muy lento",
        "baja velocidad de bajada",
        "conexion deficiente",
        "conexion lenta",
        "falta velocidad",
        "funciona lento",
        "la velocidad de internet",
        "lenta",
        "lentitud",
        "lento",
        "lerda",
        "lerdo",
        "llegan pocos megas",
        "muy baja velocidad",
        "muy lento",
        "Muy lento el Internet",
        "muy lerdo",
        "no es muy rapida",
        "no hay velocidad",
        "rapida",
        "tarda muchisimo",
        "velocidad",
        "velocidad baja",
        "velocidad inestable",
        "veloz",
    ],
    "Precio": [
        "abono elevado",
        "abono mensual",
        "abono muy caro",
        "ajustes mensuales",
        "alta factura",
        "aumenta el precio",
        "aumenta todos los meses",
        "aumentan sin avisar",
        "aumento de precio",
        "aumentos",
        "aumentos constantes",
        "cada mes más caro",
        "cada vez más caro",
        "cara",
        "carisimo",
        "caro",
        "carísima",
        "carísimo",
        "comparación con otras",
        "comparado con otras",
        "costo",
        "costo altísimo",
        "costo elevado",
        "costo muy alto",
        "costo muy elevado",
        "costo-beneficio",
        "costos",
        "costos elevados",
        "costosa",
        "costoso",
        "cuesta mucho",
        "demaciado caro",
        "demasiado cara",
        "demasiado caro",
        "demasido caro",
        "difícil de pagar",
        "es cara",
        "es caro",
        "es carísimo",
        "es muy caro",
        "es muy costoso",
        "es una estafa",
        "está muy cara",
        "está muy caro",
        "exageradamente caro",
        "excesivamente caro",
        "excesivamente costoso",
        "factura elevada",
        "hay opciones más baratas",
        "impagable",
        "imposible de pagar",
        "incremento de precio",
        "inflación",
        "injustificado",
        "lo subieron",
        "me aumentan",
        "me aumentaron",
        "me cobran",
        "me subieron",
        "monto altísimo",
        "monto elevado",
        "monto elevado",
        "muy cara",
        "muy caro",
        "muy costosa",
        "muy costoso",
        "más barato en otro lado",
        "más caro que",
        "no lo puedo pagar",
        "no se justifica el gasto",
        "no se justifica lo que cobran",
        "pagando",
        "pago mucho",
        "pesio",
        "precio",
        "precio alto",
        "precio del servicio",
        "precio elevado",
        "precio excesivo",
        "precios",
        "presio",
        "presios",
        "relación costo",
        "relación precio",
        "sin previo aviso",
        "suba",
        "suba de precio",
        "subas",
        "subas constantes",
        "suben",
        "suben el precio",
        "subida de precio",
        "subieron",
        "subió el precio",
        "tarifa",
        "tarifa alta",
        "tarifa elevada",
        "tarifa mensual",
        "valor de la tarifa",
        "valor del abono",
        "valor excesivo",
        "valores altos",
        "ya no puedo pagarlo",
    ],
    "Aviso Mora": [
        "cartel de corte",
        "se atrasa dias",
        "aviso de deuda",
        "no debo nada",
        "me llaman por deuda",
        "me llaman por algo que no debo",
        "sistema de cobro",
        "deuda de otra persona",
        "me reclaman una deuda inexistente",
        "deuda de otro usuario",
        "reclamo facturas no mias",
        "deuda que no existe",
        "ya pague y me siguen reclamando",
        "te mandan mail con deuda",
        "me llaman por deudas inexistentes",
        "reclaman pagos al día"
    ],
    "Facturación": [
        "cartel de corte",
        "se atrasa dias",
        "aviso de deuda",
        "no debo nada",
        "me llaman por deuda",
        "me llaman por algo que no debo",
        "sistema de cobro",
        "deuda de otra persona",
        "me reclaman una deuda inexistente",
        "deuda de otro usuario",
        "reclamo facturas no mias",
        "deuda que no existe",
        "ya pague y me siguen reclamando",
        "te mandan mail con deuda",
        "me llaman por deudas inexistentes",
        "reclaman pagos al día",
        "factura poco clara",
        "facturacion es confusa",
        "factura errónea",
        "error en facturación",
        "no respetan el importe de la factura",
        "me cobran lo que quieren",
        "desorden en la facturación",
        "facturación desastrosa",
        "facturación confusa",
        "facturan lo que quieren",
        "hacen desastres con la facturación",
        "no es clara la factura",
        "me cobran demas",
        "importe de la factura",
        "duplican la facturación",
        "desastres en la facturación",
        "no respetan precios",
        "no respetan promociones",
        "facturan servicios no contratados",
        "no cumplen lo pactado",
        "no hacen el descuento",
        "falta de bonificación",
        "dan de alta servicios que no se piden",
        "descuento nunca aplicado",
        "promo sin descuento",
        "nunca recibí el descuento",
        "errores continuos en la facturación",
        "irregularidades detectadas en la facturación",
        "no respetan el precio del abono",
        "me siguen cobrando",
        "nunca respetan el precio acordado",
        "me cobran cosas que no pedí",
        "no respetan lo pactado",
        "no cumplen lo prometido",
        "me cobran sin tener el servicio",
        "me cobran anticipado",
        "no puedo acceder a la factura",
        "problemas para ver la factura",
        "error de facturación",
        "me cobran servicios que no contraté",
        "me cobran de más todos los meses",
        "descuento aplicado y luego cobrado igual",
        "cobros automáticos no autorizados",
        "precio distinto al promocionado",
        "cobros inesperados",
        "errores sistemáticos en facturación",
        "problemas constantes con las facturas",
        "montos que no reconozco",
        "reclamo constante de facturación"
    ],
    "Indefinido": [
        "",
        " ",
        ".",
        "..",
        "...",
        "....",
        ".....",
        "0",
        "1",
        "10",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "nan",
        "no pt",      
        "none",
        "ok",        
        "po",
        "por",        
        "pq",
        "pt",        
        "xq",
    ],
    "Pasivos": [
        "anda bien",
        "brindan buen servicio",
        "buen servicio bien la velocidad",
        "buen servicio pero",
        "buena conexión en general",
        "buena señal",
        "casi nunca tiene contratiempos",
        "considero que es el término normal",
        "es aceptable",
        "es recomendable",
        "está bien pero no es la gran cosa",
        "ninguno. todo bien",
        "no he tenido inconvenientes significativos",
        "no respetaron un acuerdo pero buen servicio",
        "que se tiene buena señal",
        "todo bien",
    ],
    "Pagos": [
        "pago virtual",
        "no puedo pagar",
        "problemas para pagar",
        "pagar",
        "servicio limitado por falta de pago",
        "no sé cómo efectuar el pago",
        "pago",
        "pago virtual y rápida",
        "debito automático",
        "mercado pago",
        "tarjeta de credito",
        "visa",
        "descuentan cuando quieren",
        "confusa la posibilidad de abonar",
        "no puedo pagar con débito",
        "gestión de pago",
        "homebanking",
        "no logro pagar",
        "no se puede pagar",
        "cobro antes del vencimiento",
        "me cobraron mal",
        "me cobraron dos veces",
        "me cobran como si",
        "referencia de pago",
        "referencia de cuenta",
        "identificación de pago",
        "número de pago",
        "número de cuenta",
        "personal pay",
        "ppay",
        "quiero pagar y no puedo"
    ],
    "Atención Sucursal": [
        "la mala atención en la oficina",
        "la atención personalizada fue pésima",
        "regular atención en la oficina",
        "fui a la oficina"
    ],
    "Asistencia Técnica": [
        "el técnico",
        "los técnicos",
        "servicio técnico",
        "servicio tecnico",
        "cuando vino el técnico",
        "fallas en la instalación",
        "la instalación no se completó",
        "mal servicio tecnico",
        "servicio tecnico deficiente",
        "solicitar un tecnico",
        "fue el tecnico",
        "vino el tecnico",
        "no me lo instalan",
        "instalacion precaria",
        "no se realizó ningún trabajo",
        "nunca hicieron la instalación",
        "fallaron en la instalación",
        "no pudieron instalarlo",
        "no la instalaron",
        "no pudieron terminar"
    ],
    "Cita Técnica": [
        "no vinieron",
        "no viene el técnico",
        "técnico no vino",
        "cita tecnica",
        "no vienen",
        "no vino",
        "no mandan técnico",
        "nadie vino",
        "visitas técnicas",
        "esperé toda la mañana",
        "me dijeron que reagende",
        "nunca me lo instalaron",
        "me dejaron plantado",
        "me dejaron plantada",
        "fueron a otro domicilio",
        "prometieron día y hora",
        "visitas pactadas ni siquiera aparecieron",
        "bot avisó horas más tarde",
        "no cumplieron con la cita",
        "no vino el técnico",
        "no apareció el técnico",
        "el tecnico me dejo esperando",
        "no cumplieron con la visita",
        "me dieron turno y no vinieron",
        "no vino nadie al domicilio",
        "me hicieron esperar todo el día",
        "prometieron venir y no vinieron",
        "cita reprogramada sin aviso",
        "cancelaron la visita",
        "no se presentó el técnico",
        "técnico nunca vino",
        "visita técnica incumplida",
        "esperé y no vinieron",
        "turno no cumplido",
        "prometieron visita que no ocurrió",
        "incumplieron la visita técnica",
        "prometen venir",
        "sigo esperando técnico"
    ],
    "Flow": [
        "flow",
        "no funciona flow",
        "nunca pude habilitar flow",
        "TV",
        "no funciona el servicio por cable",
        "no funciona el deco",
        "cambio de deco",
        "cambio de decodificador",
        "imagen congelada",
        "mala programación",
        "imagen se congela",
        "problemas con el deco",
        "deco viejo",
        "canales no se ven",
        "no tengo flow",
        "codificador",
        "codifcadores",
        "decodificador",
        "decodificadores",
        "nitidez",
        "imagen",
        "no puedo ver",
        "todo nublado",
        "streaming",
        "deco viejo",
        "decodificador",
        "no se usar flow",
        "se corta flow",
        "flow no funciona",
        "flow se tilda",
        "flow se cuelga",
        "decodificadores",
        "control remoto",
        "guia",
        "grilla",
        "aplicacion flow",
        "app flow",
        "flow app",
        "canales",
        "no funciona el control remoto",
        "canal pago",
        "pelicula",
        "sacaron canales",
        "television",
        "programación caduca",
        "películas viejas",
        "repetición de programas",
        "programas repetidos",
        "contenido ya emitido",
        "canales que no se ven",
        "cambian horarios de series",
        "repetición de capítulos",
        "contenido desactualizado",
        "no tiene subtítulos",
        "no puedo ver programas anteriores",
        "problemas con el deco",
        "problemas para loguearme",
        "no se conecta flow",
        "problemas con la app de flow",
        "deco tildado",
        "el deco se tilda",
        "el deco funciona mal",
        "pixeleo",
        "problemas con la TV",
        "se pixela",
        "problemas con la tele con flow"
    ],
    "IVR": [
        "no atienden",
        "problema con ivr",
        "nadie me atiende",
        "atiende siempre una máquina",
        "atiende un contestador",
        "atención no personalizada",
        "no me atendieron",
        "nunca contesta una persona",
        "nunca me atienden",
        "no hay con quién hablar",
        "nadie atiende",
        "nadie contesta",
        "nadie responde",
        "no contestan",
        "no te atiende nadie",
        "no puedo comunicarme",
        "no me puedo comunicar",
        "imposible comunicarse",
        "imposible hablar",
        "hablar con un humano",
        "imposible comunicarse con un operador",
        "no dispongo contacto con operador",
        "no hay forma de hablar con alguien",
        "es difícil comunicarse",
        "llamo y no me dan la opción que necesito",
        "me pasaron con un contestador automático",
        "me contesta una máquina",
        "solo atiende un robot",
        "me atiende una máquina",
        "sólo atiende una computadora",
        "habla una grabación",
        "atención automática",
        "menú automático",
        "llamo y hay opciones infinitas",
        "llamo y hay muchas opciones",
        "llamás y nadie atiende",
        "llamás y no atienden",
        "llamé muchas veces y nada",
        "llamé 6 veces y nadie atiende",
        "llamé varias veces y no se comunicaron",
        "dificil comunicarse",
        "es muy difícil comunicarse",
        "nunca pude hablar",
        "hablar con un representante",
        "hablar con una persona",
        "hablar con un humano",
        "quiero hablar con alguien",
        "quiero hablar con una persona real",
        "quiero comunicarme con la mesa de ayuda",
        "no quiero hablar con una máquina",
        "no quiero un bot",
        "chatbot no sirve",
        "respuestas prearmadas",
        "me pasan de número en número",
        "me cortan la comunicación",
        "me pasan de un lado a otro",
        "me cansé de marcar opciones",
        "opciones que no sirven",
        "la máquina repite lo mismo",
        "todo el tiempo la misma grabación",
        "llamo y me rechazan",
        "no atiende un ser humano",
        "cuesta mucho comunicarse",
        "sin contacto humano",
        "dificultad para hablar con alguien",
        "demasiadas vueltas para atención",
        "chatbot no resuelve",
        "nadie atiende los teléfonos",
        "problema con ivr",
        "atiende un contestador"
    ],
    "Tiempos de Atención": [
        "espera de 50 minutos",
        "20 horas para que me atiendan",
        "no puedo llegar a un operador",
        "me dejan colgado",
        "media hora esperando",
        "esperas 3 hs",
        "tardan horas",
        "espera telefónica",
        "esperando con música",
        "esperar mucho",
        "tiempo no vale",
        "esperando por teléfono",
        "imposible poder hablar",
        "me pasan de un lado al otro",
        "me transfieren",
        "me derivan",
        "no me atienden",
        "me cortaron",
        "me cuelgan",
        "me cortan",
        "me ponen en espera",
        "demora para hablar",
        "tardan en atender",
        "esperar mucho",
        "espera eterna",
        "espera larga",
        "20 horas para que atiendan",
        "te hacen esperar",
        "la música en espera",
        "esperando atención",
        "esperando a que atiendan",
        "me transfieren y no atiende nadie"
    ],
    "Adultos Mayores": [
        "adulto mayor",
        "adultos mayores",
        "aumenta pero mi jubilación no",
        "bonificación de jubilada",
        "bonificación de jubilado",
        "como jubilada",
        "como jubilado",
        "edad avanzada",
        "es carísimo para jubilados",
        "es difícil para una persona mayor",
        "gente mayor",
        "jubilada",
        "jubiladas",
        "jubilado",
        "jubilados",
        "los sueldos no aumentan, yo soy jubilada",
        "mi marido también es jubilado",
        "muy caro para un jubilado",
        "no hay beneficios como jubilada",
        "no hay beneficios como jubilado",
        "no hay descuento para jubilados",
        "no me hacen bonificación de jubilada",
        "no piensan en los adultos mayores",
        "no piensan en los jubilados",
        "no puedo pagar siendo jubilado",
        "no tengo ningún beneficio con la cuota mensual",
        "personas mayores",
        "precio alto para jubilados",
        "precio muy alto para jubilado",
        "sin beneficios para jubilados",
        "sin descuento siendo jubilada",
        "soy jubilada",
        "soy jubilado",
        "soy jubilado con la mínima",
        "yo no lo puedo pagar, soy jubilado",
    ],
    "Politica Comercial": [
        "a los nuevos",
        "a los usuarios nuevos",
        "altos valores",
        "aumenta",
        "aumentan",
        "aumento",
        "aumento mensual",
        "aumentos",
        "beneficio",
        "beneficios",
        "bonificaciones",
        "bonificación",
        "caducan rápidamente",
        "carísimo",
        "cobran distinto",
        "cobran menos a los nuevos",
        "cobran más a",
        "descontar",
        "descuento",
        "descuentos",
        "desigualdad en promociones",
        "fidelidad del cliente",
        "hay que llamar cada 6 meses",
        "incremento",
        "incrementos",
        "ley de comunicación",
        "me aumentan cada rato",
        "me dijeron que iba a tener promoción",
        "me hacen llamar para pedir promoción",
        "muy caro",
        "más caro",
        "no cumplen",
        "No cumplen con lo contratado",
        "no cumplieron",
        "no hay beneficio por antigüedad",
        "no hay promociones para clientes antiguos",
        "no me dan las promociones",
        "no respetan promociones",
        "oferta",
        "ofertas",
        "ofrecen y no cumplen",
        "para clientes nuevos",
        "política de fidelidad",
        "precio",
        "precios",
        "precios elevados",
        "promo",
        "promociones",
        "promociones",
        "promoción",
        "promoción",
        "promos",
        "renovación de promociones",
        "renovar promoción",
        "renovar promos",
        "tarifa",
        "tarifas",
        "tengo que llamar para que me den un descuento",
        "usuarios antiguos pagamos más",
        "valor",
        "valores",
        "vencen las promociones",
    ],
    "Funcionamiento del Servicio": [
        "se corta",
        "a veces se corta",
        "se tilda",
        "pobre servicio",
        "pésima señal",
        "pesima señal",
        "se corta todo el tiempo",
        "servicio regular",
        "se corta muy seguido",
        "funciona muy mal",
        "reiniciar el modem",
        "el modem no funciona",
        "problemas con el modem",
        "la señal es peor desde que cambiaron",
        "cambios que afectaron el servicio",
        "funcionando muy mal",
        "cortes",
        "falla",
        "fallas",
        "faya",
        "fayas",
        "interrupciones",
        "se desconecta",
        "pérdida de señal",
        "la señal va y viene",
        "la señal se cae",
        "la señal se pierde",
        "se cuelga",
        "se cuelga el servicio",
        "servicio colgado",
        "fallas constantes",
        "fallas frecuentes",
        "funciona mal",
        "anda mal",
        "muy mal servicio",
        "pésimo servicio",
        "el servicio es un desastre",
        "no funciona bien",
        "no funciona correctamente",
        "no anda",
        "nunca anda bien",
        "mal funcionamiento",
        "no tengo servicio",
        "sin servicio",
        "no tengo internet",
        "sin conexión",
        "internet se corta",
        "no tengo wifi",
        "no tengo buena señal",
        "la señal es débil",
        "no llega el wifi",
        "poca señal",
        "baja señal",
        "alcance limitado",
        "problemas de conexión",
        "problemas de conectividad",
        "tengo que reiniciar",
        "reinicio constante",
        "hay que reiniciar",
        "servicio inestable",
        "servicio intermitente",
        "servicio deficiente",
        "servicio lento",
        "velocidad lenta",
        "velocidad baja",
        "muy lento",
        "es lento",
        "internet lento",
        "la velocidad no es la contratada",
        "la velocidad no se cumple",
        "no me dan los megas",
        "poca velocidad",
        "tengo 300 megas y no llegan",
        "nunca llegan los megas",
        "fluctuación de velocidad",
        "la conexión es inestable",
        "la red es inestable",
        "caída del servicio",
        "caídas frecuentes",
        "reclamo sin respuesta",
        "no lo solucionan",
        "no arreglan",
        "no solucionan",
        "problemas sin resolver",
        "reclamé muchas veces",
        "ya hice reclamos",
        "hice mil reclamos",
        "sin solución",
        "atención deficiente",
        "esperando solución",
        "cableado viejo",
        "no llega a domicilio",
        "anda pésimo",
        "horrible conexión",
        "malísimo",
        "no puedo trabajar",
        "imposible usar zoom",
        "me quedo sin internet",
        "streaming se interrumpe",
        "no puedo ver netflix",
        "series se cortan",
        "no se puede ver nada",
        "se corta la tele",
        "interrupción en youtube",
        "la velocidad no alcanza",
        "internet no llega a toda la casa",
        "wifi no cubre toda la casa",
        "conexión no es",
        "funciona con intermitencia",
        "deficiente servicio"
    ],
    "Microcortes": [
        "conexión yendo y viniendo",
        "continuos cortes",
        "corta y vuelve",
        "cortando",
        "cortandose",
        "cortar",
        "cortes constantes",
        "cortes frecuentes",
        "cortes intermitentes",
        "desconeccion",
        "desconecciones",
        "desconexiones",
        "desconexión",
        "el sevicio no es continuo",
        "hay intermitencias",
        "inestable",
        "internet se corta",
        "interrupciones",
        "los cortes",
        "micro corte",
        "MICRO CORTES",
        "microcortes",
        "no resolvio el problema",
        "se corta bastante",
        "se corta mucho",
        "se entre corta",
        "se interrumpe",
        "se vive cortando",
        "tiene muchos cortes",
    ],
    "Resolución": [
        "complicado resolver",
        "dando vueltas",
        "demoras en resolver",
        "no puedo resolverlo por teléfono",
        "es imposible resolverlo",
        "no puedo hacer el reclamo",
        "falta de seguimiento",
        "falta de solución",
        "me cobraron igual",
        "me dan vueltas",
        "me dijeron que",
        "me ofrecieron algo y no cumplieron",
        "me siguen reclamando",
        "mil vueltas",
        "muchas vueltas",
        "no cumplen",
        "no cumplen con lo prometido",
        "no cumplen lo que dicen",
        "no cumplieron",
        "no dan respuesta",
        "no dan respuesta clara",
        "no fue resuelto",
        "no hay respuesta",
        "no hay solución",
        "no le dan respuesta",
        "no me ayudan",
        "no me ayudaron",
        "no me han solucionado",
        "no me resolvieron",
        "no me solucionaron",
        "no me solucionó",
        "no recomendaría",
        "no responden los reclamos",
        "no resuelven",
        "no resuelven el problema",
        "no resuelven nada",
        "no se resuelve",
        "no se resuelve nada",
        "no solucionan",
        "no solucionan",
        "no solucionan los problemas",
        "no solucionan los reclamos",
        "no solucionan nada",
        "no solucionan nada de lo que pedí",
        "no solucionaron",
        "no solucionaron el problema",
        "no te dan soluciones",
        "no tiene soporte",
        "no toman en cuenta mi reclamo",
        "no toman mi inconveniente",
        "no toman mi reclamo",
        "nunca lo resolvieron",
        "nunca me llamaron",
        "obtener respuesta",
        "problema sin resolver",
        "problema sin solución",
        "problemas que no se resuelven",
        "problemas sin resolver",
        "prometieron resolver",
        "reclamo sin respuesta",
        "reclamos",
        "reclamos reiterados",
        "respuesta insatisfactoria",
        "respuesta parcial",
        "respuesta tardía",
        "resuelto parcialmente",
        "resuelven tarde",
        "servicio estable pero no resuelven",
        "sin resolver",
        "sin solución",
        "sin solución definitiva",
        "soluciones",
        "solución",
        "solución parcial",
        "tardan en resolver",
    ],
    "Atención en la Venta": [
        "comprar",
        "condiciones del abono",
        "contratar",
        "contraté",
        "lo contratado",
        "mala experiencia",
        "no informan bien",
    ],
    "App Web WhatssApp": [
        "app mi personal",
        "canal de whatsapp",
        "instagram",
        "la app movil",
        "personal pay",
        "twitter",
        "web",
        "whatsapp",
    ],
    "Móvil": [
        "celular",
        "mi celular",
        "movil",
    ],
    "Retiro Equipos": [
        "devolución de equipos",
        "retiraron el equipo",
        "retiraron modem",
    ],
    "Sin Servicio": [
        "casi un mes sin servicio",
        "cortaron el servicio",
        "corte de servicio",
        "desde que me cortaron",
        "hace días sin servicio",
        "hace meses sin servicio",
        "hace semanas sin servicio",
        "jamás me reconectaron",
        "jamás volvió el servicio",
        "me cortaron el servicio",
        "me dejaron sin internet",
        "me dejaron sin línea",
        "me dejaron sin servicio",
        "me desconectaron",
        "me lo cortaron",
        "me lo cortaron sin aviso",
        "me lo quitaron",
        "me lo suspendieron",
        "me sacaron el servicio",
        "más de un mes sin servicio",
        "no anda el internet",
        "no brindan el servicio",
        "no hay servicio",
        "no lo han arreglado",
        "no lo repusieron",
        "no me devuelven el servicio",
        "no me lo restablecen",
        "no me lo solucionaron",
        "no me reconectan",
        "no me reconectaron",
        "no me reestablecen",
        "no restablecen la línea",
        "no se reestableció",
        "no tengo conexión",
        "no tengo internet",
        "no tengo línea",
        "no tengo red",
        "no tengo servicio",
        "no tengo wifi",
        "no volvió el internet",
        "nos dejaron sin servicio",
        "sin conexión",
        "sin internet hace",
        "sin internet ni teléfono",
        "sin línea fija",
        "sin red",
        "sin servicio",
        "sin servicio desde",
        "sin señal de internet",
        "sin telefonía",
        "sin teléfono",
        "sin wifi",
    ],
    "Telefonía Fija": [
        "sin teléfono",
        "telefono",
        "telefono fijo",
        "telefonía",
        "teléfono",
    ], 
    "Contenido": [
        "pocas producciones",
        "películas viejas",
        "únicas buenas están en alquiler",
        "falta contenido en español",
        "faltan muchas series",
        "canales en inglés",
        "grilla malísima",
        "siempre las mismas series",
        "no renuevan nunca",
        "poca oferta de películas",
        "no tienen todos los packs",
        "nada nuevo para aportar",
        "contenido pobre",
        "películas mediocres",
        "el contenido no es bueno",
        "poca variedad de películas",
        "no tiene programación interesante",
        "quitaron canales",
        "quitaron AXN",
        "no se renuevan",
        "mucha publicidad y poca variedad",
        "lo que ofrecen",
        "programación repetida",
        "series repetidas",
        "flow no aporta valor"
    ],
    "TV No Compatible": [
        "no puedo ver en mi TV",
        "mi televisor ya no es compatible",
        "televisor anterior al 2020",
        "no funciona más en mi televisor",
        "no funciona en tv",
        "no puedo mirar en tv",
        "no puedo usar cualquier navegador",
        "hay que usar chrome",
        "mi tele no soporta la app",
        "ya no es compatible con mi smart tv",
        "no anda en mi televisor",
        "no se ve en mi smart tv",
        "smart tv",
        "no es compatible con mi TV"
    ],
    "App Flow": [
        "se desconecta permanentemente",
        "cuesta ingresar",
        "no es práctico",
        "tengo que activar el servicio cada vez",
        "muy poco práctico y lento",
        "se desconfigura todos los días",
        "pide autenticación todo el tiempo",
        "pierde la configuración",
        "hay que loguearse siempre",
        "problemas para ingresar a la app",
        "experiencia poco intuitiva",
        "dificultad de uso",
        "no es fácil de usar",
        "Mala app y streaming"
    ]  
}

# --- Función para normalizar frases ignorando el orden de las palabras ---
def normalizar_frase(frase):
    palabras = frase.lower().split()
    return " ".join(sorted(palabras))

# --- Diccionario con frases normalizadas (para usar en el tagging) ---
dolores_normalizados = {
    dolor: [normalizar_frase(token) for token in tokens]
    for dolor, tokens in dolores.items()
}